export const images = {
  card: require('../images/cards.png'),
  void: require('../images/void.png'),
  chip: require('../images/chip.png'),
  mastercard: require('../images/mastercard.png'),
  rupay: require('../images/rupay.png'),
  visa: require('../images/visa.png'),
  plus: require('../images/plus-white.png'),
  downArrow: require('../images/down-arrow.png'),
  brandLogo: require('../images/brand-logo.svg'),
  brandLogoPng: require('../images/brand-logo.png'),
  others: require('../images/others.png'),
  education: require('../images/education.png'),
  entertainment: require('../images/entertainment.png'),
  food: require('../images/food.png'),
  shopping: require('../images/shopping.png'),
  travel: require('../images/travel.png'),
};
