export const bankNames = [
  {code: 'SBI', name: 'State Bank of India'},
  {code: 'HDFC', name: 'HDFC Bank'},
  {code: 'ICICI', name: 'ICICI Bank'},
  {code: 'AXIS', name: 'Axis Bank'},
  {code: 'KOTAK', name: 'Kotak Mahindra Bank'},
  {code: 'CITI', name: 'Citibank'},
  {code: 'SCB', name: 'Standard Chartered Bank'},
  {code: 'BOB', name: 'Bank of Baroda'},
  {code: 'INDUSIND', name: 'IndusInd Bank'},
  {code: 'AMEX', name: 'American Express'},
  {code: 'RBL', name: 'RBL Bank'},
  {code: 'YES', name: 'Yes Bank'},
  {code: 'IDBI', name: 'IDBI Bank'},
  {code: 'CANARA', name: 'Canara Bank'},
  {code: 'FEDERAL', name: 'Federal Bank'},
  {code: 'PNB', name: 'Punjab National Bank'},
  {code: 'KARNATAKA', name: 'Karnataka Bank'},
  {code: 'HSBC', name: 'HSBC'},
  {code: 'SYNDICATE', name: 'Syndicate Bank'},
  {code: 'ANDHRA', name: 'Andhra Bank'},
  {code: 'ONECARD', name: 'One Card'},
];
